name: Output Test
on: [push, workflow_dispatch]

jobs:
    info:
        runs-on: ubuntu-latest
        steps:
        - name: Print key info
          run: |
            echo "Branch: ${{ github.ref }}"
            echo "Actor: ${{ github.actor }}"
            echo "Commit: ${{ github.sha }}"
